### ISSUE TITLE
Integrate with Travis for testing

### ISSUE THREAD

**Issue by Kikobeats** [jammus/lastfm-node#21]
I reviewed your tests and its possible integrate with travis for testing different node versions.

For example, a typical `.travis.yml` file for setup configuration are:

```
language: node_js
node_js:
  - '0.10'
  - 'VERSION_YOU_LIKE'
  - '...'
```

Also indicate in your `package.json` in the script zone the script for init the tests:

```
"scripts": {
    "test": "sh test/test.sh"
```

And activate your account in Travis. Is free :-)

**Comment by YasharF** [comment]
Travis is no longer the popular free testing service.  This issue can be closed.
