### ISSUE TITLE
Port 80 breaks API on HTTPS domains

### ISSUE THREAD

**Issue by omnichronous** [jammus/lastfm-node#28]
In the plugin settings the host is specified protocol-relative:

https://github.com/jammus/lastfm-node/blob/722b8bf22993bba5619cfcbbf3a49ddd8b39a056/lib/lastfm/index.js#L10

however the port is hardcoded to be 80

https://github.com/jammus/lastfm-node/blob/722b8bf22993bba5619cfcbbf3a49ddd8b39a056/lib/lastfm/lastfm-request.js#L42

Because of this, any request made from a HTTPS domain (like Github Pages) tries to use `https://` with port 80 and fails.

Simply removing the hardcoded port setting would fix the problem.

**Comment by jammus** [comment]
Fix merged. Will go out with next version. Thanks
